# custom tag that will be added to all saved df's and models. 
output_tag:
    'DY_validation_VBF_BDT'

#.root MC files for all years (sig and bkg) should be kept in this dir:
mc_file_dir:
    '/vols/cms/jwd18/HToEESamples/MC/'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/jwd18/HToEESamples/Data/'

mc_file_names:
    sig:
        VBF:
            #'2016': 'VBF_UL2017.root' #dont end up using this in dy plots
            '2017': 'VBF_UL2017.root'
            #'2018': 'VBF_UL2017.root'
    bkg:
        DYMC:
            #'2016': 'DY_UL2016.root'
            '2017': 'DY_UL2017.root'
            #'2018': 'DY_UL2018.root'

        EWKZlowmass:
            #'2016': 'EWKZlowmass_2016.root'
            '2017': 'EWKZlowmass_2017.root'
            #'2018': 'EWKZlowmass_2018.root'

data_file_names:
    Data:
        #'2016': 'Data_UL2016.root'
        '2017': 'Data_UL2017.root'
        #'2018': 'Data_UL2018.root'

#.root files for all years should have these tree paths. Keys should match keys above
proc_to_tree_name:
    VBF: 'Events'
    DYMC: 'Events'
    Data: 'Events'
    EWKZlowmass: 'Events'

#X variables to train with. Must be in nominal_vars (unless created from existing features)
train_vars:
    ['dijetAbsDEta', 'dijetDPhi','dijetMinDRJetEle', 'dijetMass', 
     'dijetDieleAbsDPhiTrunc', 'dijetDieleAbsDEta', 'dijetCentrality',
     'leadJetDieleDPhi', 'subleadJetDieleDPhi', 'leadJetDieleDEta', 'subleadJetDieleDEta',
     'leadElectronPtOvM', 'subleadElectronPtOvM', 'dielectronPt',
     'leadJetEn', 'leadJetPt', 'leadJetEta', 'leadJetPhi','leadJetQGL', 
     'subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL',
     'subsubleadJetEn', 'subsubleadJetPt', 'subsubleadJetEta', 'subsubleadJetPhi', 'subsubleadJetQGL', 
    # 'nSoftJets'
    ] 

vars_to_add:

# "baseline" selection that will be applied to all samples. None of these variables should be inputs!
preselection:
    'dielectronMass > 75 and dielectronMass < 105' #FIXME mass range needs to be looser since a syst with mass variations can push outisde of the nominal range. This tightness is just for mem, ideally would have no initial selection

cut_map:
    dielectronMass: ['>80','<100']
    leadElectronPtOvM: ['>0.333']
    subleadElectronPtOvM: ['>0.25']
    dijetMass: ['>250']
    leadJetPt: ['>40']
    subleadJetPt: ['>25']
