# custom tag that will be added to all saved df's and models. 
output_tag:
    'ggH_DNN'

#.root MC files for all years (sig and bkg) should be kept in this dir:
mc_file_dir:
    '/vols/cms/jwd18/HToEESamples/MC/'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/jwd18/HToEESamples/Data/'

mc_file_names:
    sig:
        ggH:
            '2016': 'ggH_UL2017.root' #re-use 2017 in 2016 for noe
            '2017': 'ggH_UL2017.root'
            '2018': 'ggH_UL2017.root' #re-use 2017 in 2018 for noe
    bkg:
        DYMC:
            '2016': 'DY_UL2016.root'
            '2017': 'DY_UL2017.root'
            '2018': 'DY_UL2018.root'

        TT2L2Nu:
            '2016': 'TTLNu_UL2016.root'
            '2017': 'TTLNu_UL2017.root'
            '2018': 'TTLNu_UL2018.root'
        TTSemiL:
            '2016': 'TTSemi_UL2016.root'
            '2017': 'TTSemi_UL2017.root'
            '2018': 'TTSemi_UL2018.root'

data_file_names:
    Data:
        '2016': 'Data_UL2016.root'
        '2017': 'Data_UL2017.root'
        '2018': 'Data_UL2018.root'

#.root files for all years should have these tree paths. Keys should match keys above
proc_to_tree_name:
    ggH: 'Events'
    DYMC: 'Events'
    Data: 'Events'
    TT2L2Nu: 'Events'
    TTSemiL: 'Events'

#X variables to train with (4 vectors of jets and QGL... anything else that is low-level and maybe useful?)
object_vars:
    [['leadJetEn', 'leadJetPt', 'leadJetEta', 'leadJetPhi','leadJetQGL'], 
     ['subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL']
     #['subsubleadJetEn', 'subsubleadJetPt', 'subsubleadJetEta', 'subsubleadJetPhi','subsubleadJetQGL']
    ]

event_vars:
    ['leadElectronPtOvM', 'subleadElectronPtOvM',
     'leadElectronEta', 'subleadElectronEta',
     'dielectronCosPhi', 'dielectronPt',
     'dijetAbsDEta', 'dijetDPhi','dijetMinDRJetEle', 'dijetMass', 
     'dijetDieleAbsDPhiTrunc', 'dijetDieleAbsDEta', 'dijetCentrality',
     'leadJetDieleDPhi', 'leadJetDieleDEta', 'subleadJetDieleDPhi', 'subleadJetDieleDEta'  
    ]

train_vars: #all vars for plotting inputs
    ['leadElectronPtOvM', 'subleadElectronPtOvM',
     'leadElectronEta', 'subleadElectronEta',
     'dielectronCosPhi', 'dielectronPt',
     'dijetAbsDEta', 'dijetDPhi','dijetMinDRJetEle', 'dijetMass', 
     'dijetDieleAbsDPhiTrunc', 'dijetDieleAbsDEta', 'dijetCentrality',
     'leadJetDieleDPhi', 'leadJetDieleDEta', 'subleadJetDieleDPhi', 'subleadJetDieleDEta',
     'leadJetEn', 'leadJetPt','leadJetEta', 'leadJetPhi','leadJetQGL', 
     'subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL',
    ]
    
vars_to_add:

#preselection that will be applied to all samples
preselection:
    'dielectronMass > 110 and dielectronMass < 150 and leadElectronPtOvM > 0.333 and subleadElectronPtOvM > 0.25'

#need looser cut for re-weighting in 80 < m_ee < 100 GeV. Apply extra cut to get into CR later
reweight_cr:
    'dielectronMass > 80 and dielectronMass < 150 and leadElectronPtOvM > 0.333 and subleadElectronPtOvM > 0.25'
